
// Meanings of Torah Portion titles
export const TORAH_PORTION_MEANINGS: { [key: string]: string } = {
  "B'reisheet": "In the beginning",
  "Noach": "Noah / Rest",
  "Lech-Lecha": "Go forth / Go for yourself",
  "Vayera": "And He appeared",
  "Chayei Sarah": "Life of Sarah",
  "Toldot": "Generations / History",
  "Vayetze": "And he went out",
  "Vayishlach": "And he sent",
  "Vayeshev": "And he dwelt",
  "Miketz": "At the end",
  "Vayigash": "And he drew near",
  "Vayechi": "And he lived",
  "Shemot": "Names / Exodus",
  "Vaera": "And I appeared",
  "Bo": "Go / Come",
  "Beshalach": "When he let go",
  "Yitro": "Jethro",
  "Mishpatim": "Laws / Judgments",
  "Terumah": "Offering / Contribution",
  "Tetzaveh": "You shall command",
  "Ki Tisa": "When you take",
  "Vayak'hel": "And he assembled",
  "Pekudei": "Accounts / Records",
  "Vayikra": "And He called",
  "Tzav": "Command",
  "Sh'mini": "Eighth",
  "Tazria-Metzora": "She conceives / Leper",
  "Acharei Mot-Kedoshim": "After the death / Holy ones",
  "Emor": "Speak",
  "Behar-Bechukotai": "On the mountain / In my statutes",
  "Bamidbar": "In the wilderness",
  "Nasso": "Take / Lift up",
  "Beha'alotcha": "When you light",
  "Shelach": "Send",
  "Korach": "Korah",
  "Chukat": "Statute / Decree",
  "Balak": "Balak",
  "Pinchas": "Phinehas",
  "Mattot-Massei": "Tribes / Journeys",
  "Devarim": "Words / Deuteronomy",
  "Va'etchanan": "And I pleaded",
  "Ekev": "Because / As a result",
  "Re'eh": "See",
  "Shoftim": "Judges",
  "Ki Tetze": "When you go out",
  "Ki Tavo": "When you enter",
  "Nitzavim": "Standing",
  "Vayelech": "And he went",
  "Ha'Azinu": "Give ear / Listen",
  "Vezot Ha'Bracha": "And this is the blessing",
};

// Themes for Torah Portions
export const TORAH_PORTION_THEMES: { [key: string]: string } = {
  "B'reisheet": "Creation of the world and humanity",
  "Noach": "The flood and God's covenant with Noah",
  "Lech-Lecha": "Abraham's call and covenant",
  "Vayera": "Abraham's visitors and the binding of Isaac",
  "Chayei Sarah": "Sarah's death and Isaac's marriage",
  "Toldot": "Isaac and his sons Jacob and Esau",
  "Vayetze": "Jacob's journey and his family",
  "Vayishlach": "Jacob wrestles with the angel",
  "Vayeshev": "Joseph's dreams and trials",
  "Miketz": "Joseph interprets Pharaoh's dreams",
  "Vayigash": "Joseph reveals himself to his brothers",
  "Vayechi": "Jacob's blessing and death",
  "Shemot": "Moses and the burning bush",
  "Vaera": "The plagues begin",
  "Bo": "The final plagues and Passover",
  "Beshalach": "Crossing the Red Sea and manna",
  "Yitro": "The Ten Commandments",
  "Mishpatim": "The laws and ordinances",
  "Terumah": "The Tabernacle offerings",
  "Tetzaveh": "The priestly garments",
  "Ki Tisa": "The golden calf and Moses' intercession",
  "Vayak'hel": "Building the Tabernacle",
  "Pekudei": "Completion of the Tabernacle",
  "Vayikra": "The laws of sacrifices",
  "Tzav": "Priestly duties",
  "Sh'mini": "Inauguration of the Tabernacle",
  "Tazria-Metzora": "Laws of purity and leprosy",
  "Acharei Mot-Kedoshim": "Day of Atonement and holiness laws",
  "Emor": "Laws for priests and holy days",
  "Behar-Bechukotai": "Sabbatical year and blessings",
  "Bamidbar": "Census in the wilderness",
  "Nasso": "Priestly blessing and Nazirite vow",
  "Beha'alotcha": "The menorah and cloud of glory",
  "Shelach": "The spies and their report",
  "Korach": "Korah's rebellion",
  "Chukat": "The red heifer and Moses' sin",
  "Balak": "Balaam blesses Israel",
  "Pinchas": "Phinehas' zeal and the census",
  "Mattot-Massei": "Vows and the journey record",
  "Devarim": "Moses begins his final address",
  "Va'etchanan": "The Shema and Ten Commandments repeated",
  "Ekev": "Blessings for obedience",
  "Re'eh": "Choose blessing or curse",
  "Shoftim": "Laws of leadership and justice",
  "Ki Tetze": "Various laws for daily living",
  "Ki Tavo": "Blessings and curses",
  "Nitzavim": "The covenant renewed",
  "Vayelech": "Moses' final instructions",
  "Ha'Azinu": "Moses' final song and witness to Israel",
  "Vezot Ha'Bracha": "Moses blesses the tribes",
};

export function extractMeaning(title: string): string {
  return TORAH_PORTION_MEANINGS[title] || title;
}

export function getThemeForPortion(title: string): string {
  return TORAH_PORTION_THEMES[title] || "";
}
